name: CI/CD

on:
    push:
        branches:
            - '**' # This will trigger the workflow on all branches
    pull_request:
        branches:
            - '**'

jobs:
    test:
        uses: ./.github/workflows/test.yml

    publish:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Tests
              uses: ./.github/workflows/test.yml

            - name: Publish package
              run: npx jsr publish
